# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 16:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('serialsnumber', models.CharField(blank=True, max_length=30, verbose_name='设备编号')),
                ('instrumenttype', models.CharField(blank=True, max_length=30, verbose_name='设备型号')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('corediameter', models.FloatField(default=0, verbose_name='纤芯直径')),
                ('claddiameter', models.FloatField(default=0, verbose_name='包层直径')),
                ('coreroundness', models.FloatField(default=0, verbose_name='纤芯不圆度')),
                ('cladroundness', models.FloatField(default=0, verbose_name='包层不圆度')),
                ('concentricity', models.FloatField(default=0, verbose_name='芯包同心度')),
                ('fibertype', models.CharField(max_length=100, verbose_name='光纤型号')),
                ('fiberLength', models.CharField(max_length=100, verbose_name='光纤长度')),
                ('fiberNo', models.CharField(max_length=100, verbose_name='光纤盘号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.Instrument', verbose_name='测试设备')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL, verbose_name='测试人员')),
            ],
            options={
                'verbose_name_plural': '测试结果',
                'verbose_name': '测试结果',
            },
        ),
    ]
