# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
    ]
